# Generated by Django 2.2.6 on 2019-10-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
    ]
